//!generate map code...
function generateMapCode() {
	
	textview = CodaPlugInsController.makeUntitledDocument();
	
	//map width & height...
	var width 				= $('#width').val();
	var height 				= $('#height').val();
	var widthUnits 			= $('#width-units').val();
	var heightUnits 		= $('#height-units').val();
	
	//map center...
	var mapLat				= $('#map-lat').val();
	var mapLng				= $('#map-lng').val();
	
	//map options...
	var mapType 			= $('#map-type').val();	
	var mapTypeStyle 		= $('#map-type-menu').val();
	var mapTypePosition 	= $('#map-type-position').val();
	var zoom				= $('#zoom').val();
	var zoomStyle 			= $('#zoom-type-menu').val();
	var zoomPosition		= $('#zoom-position').val();
	var panPosition			= $('#pan-position').val();
	var streetviewPosition	= $('#streetview-position').val();
	
	//marker...
	var markerTitle 		= $('#marker-title').val();
	var markerPath 			= $('#marker-shape').val();
	var markerColor 		= $('#marker-color').val();
	var markerOpacity 		= $('#fill-opacity').val();
	var markerLat			= $('#marker-lat').val();
	var markerLng			= $('#marker-lng').val();
	var showStroke 			= $('#show-stroke').val();
	var strokeColor 		= $('#stroke-color').val();
	var strokeWidth 		= $('#stroke-width').val();
	var strokeOpacity 		= $('#stroke-opacity').val();
	
	//infowindow...
	var infoWindowContent 	= $('#info-window').val();
	var infoWindowState 	= $('#info-window-state').val();
	var infoWindowWidth 	= $('#info-window-width').val();	
	
	//map styles...
	var showLand,
		showWater,
		showWaterLabels,
		showAdmin,
		showAdminLabels,
		showPoi,
		showRoad,
		showTrans;
	
	//map-colors...
	var landH 				= colorsArray[$('#land-h').val()];
	var landS 				= $('#land-s').val();
	var landL 				= $('#land-l').val();
	var landG				= $('#land-g').val();
	var waterH 				= colorsArray[$('#water-h').val()];
	var waterS 				= $('#water-s').val();
	var waterL 				= $('#water-l').val();
	var waterG 				= $('#water-g').val();	
	var adminH 				= colorsArray[$('#admin-h').val()];
	var adminS 				= $('#admin-s').val();
	var adminL 				= $('#admin-l').val();
	var adminG 				= $('#admin-g').val();	
	var poiH 				= colorsArray[$('#poi-h').val()];
	var poiS 				= $('#poi-s').val();
	var poiL 				= $('#poi-l').val();
	var poiG 				= $('#poi-g').val();	
	var roadH 				= colorsArray[$('#road-h').val()];
	var roadS 				= $('#road-s').val();
	var roadL 				= $('#road-l').val();
	var roadG 				= $('#road-g').val();	
	var transH 				= colorsArray[$('#trans-h').val()];
	var transS 				= $('#trans-s').val();
	var transL 				= $('#trans-l').val();
	var transG 				= $('#trans-g').val();
	
	
	var mapCode = 	'<!doctype html>\n' +
					'	<html lang="en">\n' +
					'	<head>\n' +
					'		<meta charset="utf-8" />\n' +
					'		<meta name="viewport" content="initial-scale=1.0, user-scalable=no">\n' +
					'		<title>Google Map generated by Maps Coda 2.5 Sidebar Plugin</title>\n' +
					'		\n' +
					'		<style>\n' +
					'			html, body {\n' +
					'				height: 100%;\n' +
					'				margin: 0;\n' +
					'				padding: 0;\n' +
					'			}\n' +
					'			\n' +
					'			#map-canvas {\n' +
					'				width: ' + width + widthUnits + ';\n' +
					'				height: ' + height + heightUnits + ';\n' +
					'			}\n';
	
	//infoWindow...
	if($('#add-info-window').is(':checked') && $('#show-marker').is(':checked')) {
	
		mapCode +=	'			\n' +
					'			.window-content {\n';
	
	if(infoWindowWidth.length > 0) {
		
		mapCode +=	'				width: ' + infoWindowWidth + 'px;\n';
		
	}
					
		mapCode+=	'				line-height: 1;\n' +
					'				overflow: hidden;\n' +
					'				white-space: nowrap;\n' +
					'			}\n';
	}


		mapCode +=	'		</style>\n' +
					'		\n' +
					'		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>\n' +
					'		<script>\n' +
					'			var map;\n' +
					'			function initialize() {\n' +
					'			\n' +
					'				var mapOptions = {\n' +
					'					mapTypeId: google.maps.MapTypeId.' + mapType + ',\n';

	
	//map type options...
	if($('#show-map-type').is(':checked')) {

		mapCode +=	'					mapTypeControl: true,\n' +
					'					mapTypeControlOptions: {\n' +
					'						style: google.maps.MapTypeControlStyle.' + mapTypeStyle + ',\n' +
					'						position: google.maps.ControlPosition.' + mapTypePosition + '\n' +
					'					},\n';			
	} else {
		
		mapCode +=	'					mapTypeControl: false,\n';
	}
		
		
		mapCode +=	'					zoom: ' + zoom + ',\n';
	
	
	//zoom options...
	if($('#show-zoom').is(':checked')) {
		
		mapCode +=	'					zoomControl: true,\n' +
					'					zoomControlOptions: {\n' +
					'						style: google.maps.ZoomControlStyle.' + zoomStyle + ',\n' +
					'						position: google.maps.ControlPosition.' + zoomPosition + '\n' +
					'					},\n';		
	} else {
	
		mapCode +=	'					zoomControl: false,\n';	
	}
	
	
	//pan options...
	if($('#show-pan').is(':checked')) {
		
		mapCode +=	'					panControl: true,\n' +
					'					panControlOptions: {\n' +
					'						position: google.maps.ControlPosition.' + panPosition + '\n' +
					'					},\n';		
	} else {
		
		mapCode +=	'					panControl: false,\n';
	}
	
	
	//streetview options...
	if($('#show-streetview').is(':checked')) {
		
		mapCode +=	'					streetViewControl: true,\n' +
					'					streetViewControlOptions: {\n' +
					'						position: google.maps.ControlPosition.' + streetviewPosition +'\n' +
					'					},\n';		
	} else {
		
		mapCode +=	'					streetViewControl: false,\n';
	}
	
	
	//scale options...
	if($('#show-scale').is(':checked')) {
		
		mapCode +=	'					scaleControl: true,\n';
		
	} else {
	
		mapCode +=	'					scaleControl: false,\n';	
	}
	
	
	//overview options...
	if($('#show-overview').is(':checked')) {
		
		mapCode +=	'					overviewMapControl: true,\n';
		
	} else {
	
		mapCode +=	'					overviewMapControl: false,\n';	
	}
	
	
		mapCode +=	'					center: new google.maps.LatLng(' + mapLat + ', ' + mapLng + ')\n' +
					'				};\n' +
					'				\n' +
					'				map = new google.maps.Map(document.getElementById(\'map-canvas\'),\n' +
					'					mapOptions);\n';
	
	//styled maps...
	if($('#show-styles').is(':checked')) {
		
		if($('#land').is(':checked')) {
			showLand = 'on';
		} else {
			showLand = 'off';
		}
		
		if($('#water').is(':checked')) {
			showWater = 'on';
		} else {
			showWater = 'off';
		}
		
		if($('#water-labels').is(':checked')) {
			showWaterLabels = 'on';
		} else {
			showWaterLabels = 'off';
		}
		
		if($('#admin').is(':checked')) {
			showAdmin = 'on';
		} else {
			showAdmin = 'off';
		}
		
		if($('#admin-labels').is(':checked')) {
			showAdminLabels = 'on';
		} else {
			showAdminLabels = 'off';
		}
		
		if($('#poi').is(':checked')) {
			showPoi = 'on';
		} else {
			showPoi = 'off';
		}
		
		if($('#road').is(':checked')) {
			showRoad = 'on';
		} else {
			showRoad = 'off';
		}
		
		if($('#trans').is(':checked')) {
			showTrans = 'on';
		} else {
			showTrans = 'off';
		}
		
		mapCode +=	'				\n' +
					'				var mapStyles = [\n' +
					'					{\n' +
					'						"featureType": "landscape",\n' +
					'						"stylers": [\n' +
					'							{ "visibility": "' + showLand + '" }';
	
		
	if($('#land').is(':checked') && $('#land-color').is(':checked')) {
		
		mapCode +=	',\n' +
					'							{ "hue": "' + landH + '" },\n' +
					'							{ "saturation": ' + landS + ' },\n' +
					'							{ "lightness": ' + landL + ' },\n' +
					'							{ "gamma": ' + landG + ' }';
		
	}
	
					
		mapCode +=	'\n' +
					'						]\n' +
					'					},{\n' +
					'						"featureType": "water",\n' +
					'						"stylers": [\n' +
					'							{ "visibility": "' + showWater + '" }';
	
	
	if($('#water').is(':checked') && $('#water-color').is(':checked')) {
		
		mapCode +=	',\n' +
					'							{ "hue": "' + waterH + '" },\n' +
					'							{ "saturation": ' + waterS + ' },\n' +
					'							{ "lightness": ' + waterL + ' },\n' +
					'							{ "gamma": ' + waterG + ' }';
		
	}
	
					
		mapCode +=	'\n' +
					'						]\n' +
					'					},{\n' +
					'						"featureType": "water",\n' +
					'						"elementType": "labels",\n' +
					'						"stylers": [\n' +
					'							{ "visibility": "' + showWaterLabels + '" }\n' +
					'						]\n' +
					'					},{\n' +
					'						"featureType": "administrative",\n' +
					'						"stylers": [\n' +
					'							{ "visibility": "' + showAdmin + '" }';
	
	
	if($('#admin').is(':checked') && $('#admin-color').is(':checked')) {
		
		mapCode +=	',\n' +
					'							{ "hue": "' + adminH + '" },\n' +
					'							{ "saturation": ' + adminS + ' },\n' +
					'							{ "lightness": ' + adminL + ' },\n' +
					'							{ "gamma": ' + adminG + ' }';
		
	}
					
					
		mapCode +=	'\n' +
					'						]\n' +
					'					},{\n' +
					'						"featureType": "administrative",\n' +
					'						"elementType": "labels",\n' +
					'						"stylers": [\n' +
					'							{ "visibility": "' + showAdminLabels + '" }\n' +
					'						]\n' +
					'					},{\n' +
					'						"featureType": "poi",\n' +
					'						"stylers": [\n' +
					'							{ "visibility": "' + showPoi + '" }';
	
	
	if($('#poi').is(':checked') && $('#poi-color').is(':checked')) {
		
		mapCode +=	',\n' +
					'							{ "hue": "' + poiH + '" },\n' +
					'							{ "saturation": ' + poiS + ' },\n' +
					'							{ "lightness": ' + poiL + ' },\n' +
					'							{ "gamma": ' + poiG + ' }';
		
	}
	
					
		mapCode	+=	'\n' +
					'						]\n' +
					'					},{\n' +
					'						"featureType": "road",\n' +
					'						"stylers": [\n' +
					'							{ "visibility": "' + showRoad + '" }';
	
	
	if($('#road').is(':checked') && $('#road-color').is(':checked')) {
		
		mapCode +=	',\n' +
					'							{ "hue": "' + roadH + '" },\n' +
					'							{ "saturation": ' + roadS + ' },\n' +
					'							{ "lightness": ' + roadL + ' },\n' +
					'							{ "gamma": ' + roadG + ' }';
		
	}
	
					
		mapCode	+=	'\n' +
					'						]\n' +
					'					},{\n' +
					'						"featureType": "transit",\n' +
					'						"stylers": [\n' +
					'							{ "visibility": "' + showTrans + '" }';
	
	
	if($('#trans').is(':checked') && $('#trans-color').is(':checked')) {
		
		mapCode +=	',\n' +
					'							{ "hue": "' + transH + '" },\n' +
					'							{ "saturation": ' + transS + ' },\n' +
					'							{ "lightness": ' + transL + ' },\n' +
					'							{ "gamma": ' + transG + ' }';
		
	}
	
					
		mapCode	+=	'\n' +
					'						]\n' +
					'					}\n' +
					'				];\n';
		
		mapCode +=	'				\n' +
					'				map.setOptions({styles: mapStyles});\n';
		
	}
	
	
	//traffic layer...
	if($('#traffic').is(':checked')) {
		
		mapCode +=	'				\n' +
					'				var trafficLayer = new google.maps.TrafficLayer();\n' +
					'				trafficLayer.setMap(map);\n';		
	}
	
	
	//transit layer...
	if($('#transit').is(':checked')) {
		
		mapCode +=	'				\n' +
					'				var transitLayer = new google.maps.TransitLayer();\n' +
					'				transitLayer.setMap(map);\n';		
	}
	
	
	//bicycling layer...
	if($('#bicycling').is(':checked')) {
		
		mapCode +=	'				\n' +
					'				var bicyclingLayer = new google.maps.BicyclingLayer();\n' +
					'				bicyclingLayer.setMap(map);\n';		
	}
	
	
	//infowindow...
	if($('#add-info-window').is(':checked') && $('#show-marker').is(':checked')) {
		
		mapCode += 	'				\n' +
					'				var infoContent = \'<div class="window-content">' + infoWindowContent + '</div>\';\n' +
					'				\n' +
					'				var infowindow = new google.maps.InfoWindow({\n' +
					'					content: infoContent\n' +
					'				});\n';	
		
	}
	
	
	//marker...
	if($('#show-marker').is(':checked')) {
	
		//marker icon path and co-ordinates...
		var iconPath, iconX, iconY;
	
		switch ($('#marker-shape').val()) {
			
			case 'pin':
				
				iconPath 	= pin;
				iconX 		= pinX;
				iconY 		= pinY;
				break;
				
			case 'star':
				
				iconPath 	= star;
				iconX 		= starX;
				iconY 		= starY;
				break;
				
			case 'circle':
				
				iconPath 	= circle;
				iconX 		= circleX;
				iconY 		= circleY;
				break;
				
			case 'flag':
				
				iconPath 	= flag;
				iconX 		= flagX;
				iconY 		= flagY;
				break;
			
			default:
				
				iconPath 	= shield;
				iconX 		= shieldX;
				iconY 		= shieldY;
		}		
		
		var iconSize;
	
		switch ($('#marker-size').val()) {
			
			case 'small':
				
				iconSize 	= 0.66;
				break;
			
			case 'medium':
				
				iconSize 	= 1;
				break;
			
			default:
			
				iconSize 	= 1.33;	
		}
	
	//marker icon...
		mapCode +=	'				\n' +
					'				var icon = {\n' +
					'					path: \'' + iconPath + '\',\n' +
					'					anchor: new google.maps.Point(' + iconX + ', ' + iconY + '),\n' +
					'					fillColor: \'' + markerColor + '\',\n' +
					'					fillOpacity: ' + markerOpacity + ',\n';
		
	//marker stoke...
	if($('#show-stroke').is(':checked')) {
					
		mapCode +=	'					strokeWeight: ' + strokeWidth + ',\n' +
					'					strokeColor: \'' + strokeColor + '\',\n' + 
					'					strokeOpacity: ' + strokeOpacity + ',\n';
						
	} else {
	
		mapCode +=	'					strokeWeight: 0,\n';
		
	}
		
		
		mapCode +=	'					scale: ' + iconSize + '\n' +
					'				};\n';
					
		
		mapCode +=	'				\n' +
					'				var marker = new google.maps.Marker({\n' +
					'					position: new google.maps.LatLng(' + markerLat + ', ' + markerLng + '),\n' +
					'					map: map,\n' +
					'					icon: icon,\n' +
					'					title: \'' + markerTitle + '\'\n' +
					'				});\n';
		
	}//end if marker...
	
	
	//if infowindow...
	if($('#add-info-window').is(':checked') && $('#show-marker').is(':checked')) {
		
		mapCode +=	'				\n' +
					'				google.maps.event.addListener(marker, \'click\', function() {\n' +
					'					infowindow.open(map,marker);\n' +
					'				});\n';
		
		//if infowindow is open...	
		if($('#info-window-state').val() === 'true') {	
		
		mapCode +=	'				\n' +
					'				infowindow.open(map, marker);\n';
		}	
	}
	

	
		mapCode +=	'			}\n' +
					'			\n' +
					'			google.maps.event.addDomListener(window, \'load\', initialize);\n' +
					'			\n';
	
	//if map is responsive...
	if(	widthUnits 		=== '%'		||
		widthUnits 		=== 'vw'	||
		widthUnits 		=== 'vh'	||
		heightUnits 	=== '%'		||
		heightUnits 	=== 'vw'	||
		heightUnits 	=== 'vh'	) {
		
		
		mapCode +=	'			function checkResize(){\n' +
					'			\n' +
					'				var center = map.getCenter();\n' + 
					'				google.maps.event.trigger(map, \'resize\');\n' + 
					'				map.setCenter(center);\n' + 
					'			}\n' +
					'			\n' +
					'			window.onresize = checkResize;' +
					'			\n';		
	}
					
		mapCode +=	'		</script>\n' +
					'	</head>\n' +
					'	\n' +
					'	<body>\n' +
					'		<div id="map-canvas"></div>\n' +
					'	</body>\n' +
					'</html>\n';
	
	window.CodaTextView.insertText(mapCode);
	
}
